import Head from 'next/head'
import cryptoJs from 'crypto-js';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

const secretKey = 'Secret Passphrase'
const iv  = cryptoJs.enc.Hex.parse('be410fea41df7162a679875ec131cf2c');
export default function Home() {
  const [text,setText] = useState('')
  const [textEncrypted,setTextEncrypted] = useState()
  const [textDecrypted,setTextDecrypted] = useState()

  useEffect(() => {
    const encrypted  = cryptoJs.AES.encrypt(text, secretKey, 
      {
        iv,
        mode: cryptoJs.mode.CBC,
        padding: cryptoJs.pad.Pkcs7
    });
    setTextEncrypted(encrypted.toString())
    
  }, [text])

  useEffect(()=>{
    try{
      const decrypted  = cryptoJs.AES.decrypt(textEncrypted, secretKey, {
        iv,
        mode: cryptoJs.mode.CBC,
        padding: cryptoJs.pad.Pkcs7
      });
      console.log({decrypted, textEncrypted});
      setTextDecrypted(decrypted.toString(cryptoJs.enc.Utf8) || 'error')
      
    }catch(err) {
      setTextDecrypted('Error al decifrar texto')
    }
  },[textEncrypted])



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Test Crypto JS with React JS
        </h1>

      
        <div className={styles.grid}>
         
         <textarea onChange={(e) => setText(e.target.value)} >{text}</textarea>

        </div>
<div style={{flex:1, display: 'flex', width: '100%'}}>
         <h3>textDecrypted</h3>
         <p>
           {textDecrypted}
         </p>

</div>
<div style={{flex:1, display:'flex', width: '100%'}}>
         <h3>textEncrypted</h3>
         <p>
           {textEncrypted}
         </p>

</div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
